import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(req: NextRequest) {
  try {
    const { email, result } = await req.json()
    if (!email || !result?.analysis) {
      return NextResponse.json({ error: 'Missing data' }, { status: 400 })
    }

    const { analysis, url, platform, pagesAnalyzed } = result
    const scores = analysis.scores

    const htmlContent = `
      <div style="font-family: system-ui, sans-serif; max-width: 600px; margin: 0 auto; color: #e4e4e7; background: #0a0a0f; padding: 32px; border-radius: 12px;">
        <h1 style="color: #ffffff; font-size: 24px; margin-bottom: 4px;">AI Agent Assessment</h1>
        <p style="color: #9ca3af; font-size: 14px; margin-bottom: 24px;">${analysis.businessName} | ${url}</p>
        
        <h2 style="color: #ffffff; font-size: 18px; margin-top: 24px;">Scores</h2>
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
          <tr><td style="padding: 8px 0; color: #9ca3af; font-size: 14px;">Response Capability</td><td style="text-align: right; color: #00d4ff; font-weight: bold;">${scores.responseCapability.score}/10</td></tr>
          <tr><td style="padding: 4px 0; color: #6b7280; font-size: 12px;" colspan="2">${scores.responseCapability.reasoning}</td></tr>
          <tr><td style="padding: 8px 0; color: #9ca3af; font-size: 14px;">Lead Capture</td><td style="text-align: right; color: #00d4ff; font-weight: bold;">${scores.leadCapture.score}/10</td></tr>
          <tr><td style="padding: 4px 0; color: #6b7280; font-size: 12px;" colspan="2">${scores.leadCapture.reasoning}</td></tr>
          <tr><td style="padding: 8px 0; color: #9ca3af; font-size: 14px;">Content Completeness</td><td style="text-align: right; color: #00d4ff; font-weight: bold;">${scores.contentCompleteness.score}/10</td></tr>
          <tr><td style="padding: 4px 0; color: #6b7280; font-size: 12px;" colspan="2">${scores.contentCompleteness.reasoning}</td></tr>
          <tr><td style="padding: 8px 0; color: #9ca3af; font-size: 14px;">AI Readiness</td><td style="text-align: right; color: #00d4ff; font-weight: bold;">${scores.aiReadiness.score}/10</td></tr>
          <tr><td style="padding: 4px 0; color: #6b7280; font-size: 12px;" colspan="2">${scores.aiReadiness.reasoning}</td></tr>
        </table>

        <h2 style="color: #ffffff; font-size: 18px; margin-top: 24px;">Key Observations</h2>
        <ul style="padding-left: 16px; color: #d1d5db; font-size: 14px; line-height: 1.8;">
          ${analysis.observations.map((o: string) => `<li>${o}</li>`).join('')}
        </ul>

        <h2 style="color: #ffffff; font-size: 18px; margin-top: 24px;">Questions Your Agent Would Handle</h2>
        <ul style="padding-left: 16px; color: #d1d5db; font-size: 14px; line-height: 1.8;">
          ${analysis.topQuestions.map((q: string) => `<li>"${q}"</li>`).join('')}
        </ul>

        <h2 style="color: #ffffff; font-size: 18px; margin-top: 24px;">Our Recommendation</h2>
        <p style="color: #d1d5db; font-size: 14px; line-height: 1.6;">${analysis.recommendation}</p>

        <div style="margin-top: 32px; padding-top: 24px; border-top: 1px solid #1f1f2e;">
          <p style="color: #6b7280; font-size: 12px;">Pages analyzed: ${pagesAnalyzed.join(', ')} | Platform: ${platform}</p>
          <p style="color: #6b7280; font-size: 12px; margin-top: 8px;">Generated by FundyLogic | <a href="https://fundylogic.com" style="color: #00d4ff;">fundylogic.com</a></p>
        </div>
      </div>
    `

    // Send to the user
    await resend.emails.send({
      from: 'FundyLogic <reports@fundylogic.com>',
      to: email,
      subject: `AI Agent Assessment: ${analysis.businessName}`,
      html: htmlContent,
    })

    // Also notify us (lead captured)
    await resend.emails.send({
      from: 'FundyLogic <reports@fundylogic.com>',
      to: 'info@fundylogic.com',
      subject: `[Lead] Report requested: ${analysis.businessName} (${email})`,
      html: `<p>Someone requested their AI assessment report.</p><p><strong>Email:</strong> ${email}</p><p><strong>Business:</strong> ${analysis.businessName}</p><p><strong>URL:</strong> ${url}</p><p><strong>Type:</strong> ${analysis.businessType}</p>`,
    })

    return NextResponse.json({ success: true })
  } catch (err) {
    console.error('Email report error:', err)
    return NextResponse.json({ error: 'Failed to send' }, { status: 500 })
  }
}
